account/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, url

# django.contrib
urlpatterns = patterns('',
   # Feeds
    (r'^password_reset/$', 'django.contrib.auth.views.password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)

urlpatterns += patterns('account.forms',
    url(r'^signup/$', 'create_new_user', name="signup"),
    url(r'^askpassword/$', 'reset_password', name="resetpassword"),
    url(r'^profil/$', 'edit_profil', name='editprofil'),
    url(r'^profil/deleteavatar/$', 'deleteavatar', name='deleteavatar'),
    url(r'^profil/mysubscriptions/$', 'edit_profil_subscriptions', name='editprofilsubscriptions'),
    url(r'^profil/changepassword/$', 'changepassword', name='changepassword'),
)

urlpatterns += patterns('account.views',
    url(r'^notification/$', 'view_notification', name='viewnotification'),
    url(r'^notification/markasread/$', 'markasread_notification', name='markasreadnotification'),
    url(r'^login/$', 'login',
        {'next_page': settings.SITE_ROOT},
        name="login"),
    url(r'^logout/$', 'logout',
        {'next_page': settings.SITE_ROOT},
        name="logout"),
    url(r'^profil/(?P<user_pk>\d+)/view/$', 'view_profil', name='viewprofil'),
)

urls.py
from django.conf.urls.defaults import patterns, url, include
from django.contrib import admin
from djblets.util.misc import generate_cache_serials
from django.conf import settings
import os
from admin.forms import GeneralSettingsForm

# Generate cache serials
generate_cache_serials()

if not admin.site._registry:
    admin.autodiscover()

cal_path = os.path.dirname(__file__)
urlpatterns = patterns('',
    (r'^robots\.txt$', 'django.views.static.serve', {'path':'robots.txt', 'document_root': cal_path, 'show_indexes': True}),
    (r'^bc38928ca88b5eaeb8eac84640c15074\.txt$', 'django.views.static.serve', {'path':'bc38928ca88b5eaeb8eac84640c15074.txt', 'document_root': cal_path, 'show_indexes': True}),
    url(r'^search/$', 'django.views.generic.simple.direct_to_template', {'template':'search.html', 'extra_context':{'full':True}}, name="search"),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^article/', include('article.urls')),
    (r'^lien/', include('article.lien_urls')),
    (r'^account/', include('account.urls')),
    (r'^forum/', include('forum.urls')),
    (r'^galerie/', include('galerie.urls')),
    (r'^photologue/', include('photologue.urls')),
    (r'^sortie/', include('sortie.urls')),
    (r'^comment/', include('comment.urls')),
    (r'^captcha/', include('captcha.urls')),
    (r'^core/', include('core.urls')),
    (r'^matos/', include('matos.urls')),
    (r'^meteo/', include('meteo.urls')),
#    (r'^browse/(.*)', login_required(databrowse.site.root)),
)

# And the rest ...
urlpatterns += patterns('',
    url(r'^$', 'article.views.accueil', name="root"),
    url(r'^about/$', 'article.views.about', name="aboutus"),
    url(r'^contactus/$', 'account.forms.contact_us', name="contactus"),
    (r'^secure/(?P<path>.*)$', 'core.views.serve', {
        'show_indexes': True,
        'document_root': settings.SECURE_ROOT,
        }),
)

# Adding the site settings page
urlpatterns += patterns('',
    url(r'admin/settings/general/$', 'djblets.siteconfig.views.site_settings',
     {'form_class': GeneralSettingsForm}, name="site_setup"))

# Add static media
import djblets
import django.contrib.admin
djblets_media_path = os.path.join(os.path.dirname(djblets.__file__), 'media')
admin_media_path = os.path.join(os.path.dirname(django.contrib.admin.__file__), 'media')
urlpatterns += patterns('django.views.static',
    (r'^media/admin/(?P<path>.*)$', 'serve', {
        'show_indexes': True,
        'document_root': admin_media_path,
        }),
    (r'^media/djblets/(?P<path>.*)$', 'serve', {
        'show_indexes': True,
        'document_root': djblets_media_path,
        }),
    (r'^media/(?P<path>.*)$', 'serve', {
        'show_indexes': True,
        'document_root': settings.MEDIA_ROOT,
        }),
)

account/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from photologue.models import Photo
from django.core.urlresolvers import reverse
from log.models import LogActivity

class Profil(models.Model):
    user = models.ForeignKey(User, default=1)
    lieu = models.TextField(null=True, blank=True)
    telephone = models.TextField(null=True, blank=True)
    avatar = models.ForeignKey(Photo, null=True, blank=True, related_name='avatar_set')
    gravatarurl = models.TextField(null=True, blank=True)
    signature = models.TextField(null=True, blank=True)
    siteweb = models.TextField(null=True, blank=True)
    custom_background_image = models.CharField(max_length=255, null=True, blank=True)
    discussions = models.ManyToManyField("forum.Thread", 
                                         related_name='discussions_suivies_set',
                                         null=True, blank=True)
    forums = models.ManyToManyField("forum.Forum", 
                                         related_name='forums_suivis_set',
                                         null=True, blank=True)
    articles = models.ManyToManyField("article.Article", 
                                         related_name='articles_suivis_set',
                                         null=True, blank=True)
    sorties = models.ManyToManyField("sortie.Sortie", 
                                         related_name='sorties_suivies_set',
                                         null=True, blank=True)
    galeries = models.ManyToManyField("galerie.Galerie", 
                                         related_name='galeries_suivies_set',
                                         null=True, blank=True)
    suivre_les_articles = models.BooleanField(default=True)
    suivre_les_sorties = models.BooleanField(default=True)
    suivre_les_sorties_partype = models.ManyToManyField("sortie.Activite", 
                                         related_name='activites_suivies_set',
                                         null=True, blank=True)
    suivre_les_compterendus = models.BooleanField(default=True)
    suivre_les_discussions = models.BooleanField(default=True)
    suivre_les_galeries = models.BooleanField(default=True)
    auto_refresh_notif = models.BooleanField(default=False)
    last_known_activity = models.ForeignKey(LogActivity, related_name='last_known_activity_set', null=True, blank=True)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "%s (%s - %s)" % (self.user.username, self.lieu, self.telephone)
    
    def get_avatar_url(self):
        url = "/media/images/default-avatar.png"
        if self.gravatarurl:
            url = self.gravatarurl
        elif self.avatar:
            urltmp = self.avatar.get_avatar_url()
            _file = self.avatar.image.path 
            try:
                import os
                if os.path.isfile(_file):
                    url = urltmp
            except:
                pass
        return url

    def get_avatar_full_url(self):
        url = "/media/images/default-avatar.png"
        if self.gravatarurl:
            url = self.gravatarurl
        elif self.avatar:
            urltmp = self.avatar.image.url
            _file = self.avatar.image.path 
            try:
                import os
                if os.path.isfile(_file):
                    url = urltmp
            except:
                pass
        return url

    def get_html_avatar(self, cssclass="avatar"):
        html = "<a href='%s'><img width='50px' height='50px' class='%s' src='%s' alt='%s'/></a>" % (reverse("viewprofil", kwargs={'user_pk':self.user.pk}), cssclass, self.get_avatar_url(), self.user.username)
        return html

    def get_html_illustration(self):
        return self.get_html_avatar(cssclass="illustration")

account/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.template.context import RequestContext
from djblets.auth.util import internal_login
from account.models import Profil
import urllib
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from log.models import LogActivity
from django.contrib.contenttypes.models import ContentType
from sortie.models import Participant
from django.core.urlresolvers import reverse
from account.decorators import login_required

###########################
#       User Login        #
###########################

def login(request, next_page, next_query=None, template_name="accounts/login.html"):
    """Simple login form view which doesn't rely on Django's current
       inflexible oldforms-based auth view.
    """

    error = None
    if request.POST:
        request.session.set_test_cookie()
        loginbox = request.POST.get('loginbox')
        error = internal_login(request,
                               request.POST.get('username'),
                               request.POST.get('password'))
        urlnext = request.REQUEST.get("next_page", next_page)
        query = request.REQUEST.get("next_query", next_query)
        if query and not query == "None":
            try:
                urlnext += "?%s" % urllib.unquote_plus(query)
            except:
                pass
        if not error or loginbox:
            response = HttpResponseRedirect(urlnext)
            if error:
                response.set_cookie('loginerror',
                            value=error,
                            max_age='%s' % (5), # in seconds
                            path=settings.SITE_ROOT,
                            )
            else:
                response.delete_cookie('loginerror', path=settings.SITE_ROOT)
            return response

    request.session.set_test_cookie()
    context = RequestContext(request, {
        'error' : error,
        'login_url' : settings.LOGIN_URL,
        'full': True,
        'next_page' : request.REQUEST.get("next_page", next_page),
        'next_query' : request.REQUEST.get("next_query", next_query),
    })
    return render_to_response(template_name, context)

def logout(request, next_page=None, next_query=None, template_name='registration/logged_out.html', redirect_field_name=REDIRECT_FIELD_NAME):
    "Logs out the user and displays 'You are logged out' message."
    from django.contrib.auth import logout
    logout(request)

    urlnext = request.REQUEST.get("next_page", next_page)
    query = request.REQUEST.get("next_query", next_query)
    if query and not query == "None":
        urlnext += "?%s" % urllib.unquote_plus(query)
    return HttpResponseRedirect(urlnext)
    
@login_required
def view_profil(request, user_pk, template_name='accounts/profil_view.html'):
    u = get_object_or_404(User, pk=user_pk)
    p = None
    try:
        p = u.get_profile()
    except Profil.DoesNotExist:
        p = Profil(user=u)
        p.save()

    return render_to_response(template_name, RequestContext(request, {'profil': p, 'p': p,}))

class Notification:
    def __init__(self, activity, last_known_activity):
        self.activity = activity
        self.is_new = activity.pk > last_known_activity.pk
    
    def to_html(self):
        html = str(self.activity)
        if self.is_new:
            html = "<strong>%s</strong>" % html
        return html

@login_required
def view_notification(request, template_name='accounts/notification_view.html'):
    p = request.user.get_profile()
    notifications = {}
    norefresh = request.GET.get("norefresh")
    activities = LogActivity.objects.exclude(qui=request.user).exclude(type=ContentType.objects.get_for_model(Participant)).order_by("-pk")[:50]
    for a in activities:
        if not notifications.get(a.date.date()):
            notifications[a.date.date()] = []
        notifications[a.date.date()].append(Notification(a, p.last_known_activity))

    notifications = [(k, notifications[k]) for k in sorted(notifications, reverse=True)]
    return render_to_response(template_name, RequestContext(request, {'notifications': notifications,'norefresh': norefresh,}))

@login_required
def markasread_notification(request):
    p = request.user.get_profile()
    p.last_known_activity = LogActivity.getDefault()
    p.save()
    return HttpResponseRedirect(reverse("viewnotification")+"?norefresh=1")

templates/accounts/avatar.html

{% if p.gravatarurl %}
    <img src="{{ p.gravatarurl }}" /> 
{% else %} {% if p.avatar %} 
    <img src="{{ p.avatar.get_avatar_url }}" alt="{{ p.avatar.title }}" /> 
{% endif %} {% endif %}

templates/accounts/change_password.html

 <form id="password_form" method="POST" action="{% url changepassword %}">
 <table>
    <tbody>
      <tr>
       <td class="label"><label for="id_pass1">Password:</label></td>
       <td class="field"><input type="password" name="pass1" id="id_pass1" value="" size="75" /></td>
      </tr>
      <tr>
       <td class="label"><label for="id_pass2">Retype password:</label></td>
       <td class="field"><input type="password" name="pass2" id="id_pass2" value="" size="75" /></td>
      </tr>
    </tbody> 
 </table>
</form>

templates/accounts/contact_form.html
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}

<h2>Contact</h2>
<p class="warn">Vous pouvez choisir de contacter le Bureau ou le Conseil d'Administration ou bien le Webmaster.</p>

<form action="." method="post">
{{form.as_p}}
<p><input type="submit" class="awesome green" value="Envoyer"></p>
</form>

{% endblock %}

templates/accounts/contact_form_sent.html
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}

<p>Votre message a bien &eacute;t&eacute; envoy&eacute;.</p>
<p>Nous y r&eacute;pondrons aussi rapidement que possible.</p>
<p><a href="{% url root %}">Retour au site</a>.</p>

{% endblock %}

templates/accounts/edit_profil_form.html
{% extends "base.html" %}

{% block title %}Mon Profil{% endblock %}

{% block content %}
<div id="profil" class="profil">
    <img class="avatar right" alt="" src="{{user.get_profile.get_avatar_url}}">
	<h2>{{user.username}}</h2>
    
<form method="post" action="." enctype="multipart/form-data">
	<h3>Mon avatar</h3>
	{{avatarform.as_p}}
	<p><label for="id_avatardelete">Cliquez ici pour effacer votre avatar enregistr&eacute;:</label> <a id="id_avatardelete" href="{% url deleteavatar %}">Suppression de mon avatar</a></p>
	<h3>Mon compte</h3>
    {{userform.as_p}}
	<h3>Mon mot de passe</h3>
	<p class="warn">Laissez tous les champs vides si vous ne voulez pas changer de mot de passe.</p>
    {{passwordform.as_p}}
	<h3>Mes donn&eacute;es personnelles</h3>
    {{profilform.as_p}}

	<p><input class="awesome green" value="Valider" type="submit"> <input class="awesome blue tooltip" type="button" title="Voir mes abonnements" value="Voir mes abonnements" onclick="javascript:window.location='{% url editprofilsubscriptions %}';" /></p>
</form>

</div>

<script type="text/javascript">
$(document).ready(function(){
	if ($("#id_suivre_les_sorties").attr("checked") == "checked") {
		$("#id_suivre_les_sorties_partype").prop('disabled', true);
		$('label[for="id_suivre_les_sorties_partype"]').addClass("disabledlabel");
	}
	$("#id_suivre_les_sorties").click(function() {
		if ($("#id_suivre_les_sorties").attr("checked") == "checked") {
			$("#id_suivre_les_sorties_partype").prop('disabled', true);
			$('label[for="id_suivre_les_sorties_partype"]').addClass("disabledlabel");
		} else {
			$("#id_suivre_les_sorties_partype").prop('disabled', false);
			$('label[for="id_suivre_les_sorties_partype"]').removeClass("disabledlabel");
		}
	});
});
</script>
{% endblock %}

templates/accounts/edit_profil_subscriptions.html
{% extends "base.html" %}

{% block title %}Mes Abonnements{% endblock %}

{% block content %}
<div class="profil">
	<h2>Mes Abonnements</h2>
	<h3 id="articles">Les Articles</h3>
	<ul>
	{% for a in user.get_profile.articles.all %}
	<li><a title="{{a.titre}}" href="{{a.get_absolute_url}}">{{a.titre}}</a> <a title="Se d&eacute;sabonner" href="{% url unsubscribearticle a.titre_slug %}?next_page={% url editprofilsubscriptions %}#articles" class="awesome red ultratiny right">se d&eacute;sabonner</a></li>
	{% endfor %}
	</ul>
	
	<h3 id="sorties">Les Activit&eacute;s</h3>
	<ul>
	{% for s in user.get_profile.sorties.all %}
	<li><a title="{{s.titre}}" href="{{s.get_absolute_url}}">{{s.titre}}</a> <a title="Se d&eacute;sabonner" href="{% url unsubscribesortie s.titre_slug %}?next_page={% url editprofilsubscriptions %}#sorties" class="awesome red ultratiny right">se d&eacute;sabonner</a></li>
	{% endfor %}
	</ul>

	<h3 id="discussions">Les Discussions</h3>
	<ul>
	{% for t in user.get_profile.discussions.all %}
	<li><a title="{{t.titre}}" href="{{t.get_absolute_url}}">{{t.titre}}</a> <a title="Se d&eacute;sabonner" href="{% url unsubscribethread t.titre_slug %}?next_page={% url editprofilsubscriptions %}#discussions" class="awesome red ultratiny right">se d&eacute;sabonner</a></li>
	{% endfor %}
	</ul>

	<h3 id="galeries">Les Galeries</h3>
	<ul>
	{% for g in user.get_profile.galeries.all %}
	<li><a title="{{g.titre}}" href="{{g.get_absolute_url}}">{{g.titre}}</a> <a title="Se d&eacute;sabonner" href="{% url unsubscribegalerie g.imgur_id %}?next_page={% url editprofilsubscriptions %}#galeries" class="awesome red ultratiny right">se d&eacute;sabonner</a></li>
	{% endfor %}
	</ul>

</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Connectez-vous{% endblock %}

{% block content %}
<h2>Nouveau ?</h2>
<p>Si vous n'avez pas encore de compte, vous pouvez <a href="{% url signup %}">devenir membre</a>.</p>

<h2>Connectez-vous</h2>
<p><a href="{% url resetpassword %}">Identifiants oubli&eacute;s ?</a></p>
<form method="post" action=".">
	{% if error %}
	<ul class="errorlist"><li>{{error}}</li></ul>
	{% endif %}
	<p><input type="hidden" name="next_page" value="{{next_page}}" /></p>
	<p><input type="hidden" name="next_query" value="{{next_query}}" /></p>
	<p><label for="id_username">Pseudo :</label><input type="text" name="username" id="id_username" /></p>
	<p><label for="id_password">Mot de passe :</label><input type="password" name="password" id="id_password" /></p>
	<p><input class="awesome green" value="Valider" type="submit"></p>
</form>

{% endblock %}

templates/accounts/notification_view.html
{% extends "base.html" %}
{% block title %}Tes notifications{% endblock %}

{% block content %}
<p class="suggest right"><a class="awesome blue" href="{% url markasreadnotification %}">Marquer les notifications comme lues</a></p>
<div id="notifications">
    {% for item in notifications %}
    <h2>{{item.0|date:"l d F Y"}}</h2>
    <ul>
    	{% for n in item.1 %}
    	<li>{{n.to_html|safe}}</li>
    	{% endfor %}
    </ul>
    {% endfor %}
</div>

{% if user.get_profile.auto_refresh_notif %}
{% if not norefresh %}
<script>
    $(document).ready(function() {
    	setTimeout("$('body').load('{% url markasreadnotification %}');", 5000);
    });
</script>
{% endif %}
{% endif %}

{% endblock %}

templates/accounts/profil.html
{% if p %}
<dl>
	<dt><strong><a href="{% url viewprofil user_pk=p.user.pk %}">{{ p.user.username }}</a></strong></dt>
	<dd>{% include "accounts/avatar.html" %}</dd>
	<dd>Date d'inscription: {{ p.date_creation.date|date:"d/m/Y" }}</dd>
	<dd>Messages: {{ messagescount }}</dd>
	<dd>
	{% if p.siteweb %}
	   <a href="{{ p.siteweb }}">Site web</a>
	{% endif %}
	</dd>
</dl>
{% endif %}

templates/accounts/profil_view.html
{% extends "base.html" %}
{% block title %}Profil de {{profil.user.username}}{% endblock %}

{% if profil %}
{% block content %}


<div class="profil">
    <img class="avatar right" alt="" src="{{profil.get_avatar_full_url}}">
	<h2>{{profil.user.username}}</h2>
    
        
	<h3>Dans la vraie vie</h3>
    <ul>
    <li>Nom : {{profil.user.first_name}} {{profil.user.last_name}}</li>
    <li>Lieu : {{profil.lieu}}</li>
    {% if profil.siteweb %}
	<li><a href="{{profil.siteweb}}">{{profil.siteweb}}</a></li>
	{% endif %}
	</ul>
      
  
    <h3>Sur le Site des CAL</h3>
    <ul>
    	<li class="ico-arrow">Inscrit depuis le {{profil.user.date_joined.date|date:"l d F Y"}}</li>
		<li class="ico-arrow">{{profil.user.auteur_message_set.all.count}} messages sur le <a href="{% url groupes %}">forum</a></li>
		<li class="ico-arrow">{{profil.user.comment_auteur_set.all.count}} commentaires</li>
		<li class="ico-arrow" id="showdocs-actu"><a href="{% url articles %}?auteur={{profil.user.pk}}">{{profil.user.auteur_set.all.count}} Articles</a>
		<li class="ico-arrow" id="showdocs-actu"><a href="{% url sorties %}?auteur={{profil.user.pk}}">{{profil.user.sortie_auteur_set.all.count}} Sorties propos&eacute;es</a>
	</ul>
  </div>

{% endblock %}
{% endif %}

templates/accounts/reset_password_form.html
{% extends "base.html" %}

{% block title %}Mot de passe perdu{% endblock %}

{% block content %}

<h2>Votre mot de passe</h2>
<h3>Mot de passe perdu ?</h3>

<form method="post" action=".">
	<p>Afin de retrouver votre mot de passe, indiquez votre e-mail :</p>
	{{form.as_p}}
	<p><input class="awesome green" value="Valider" type="submit"></p>
</form>  
  
{% endblock %}

templates/accounts/user_create_form.html
{% extends "base.html" %}
{% load preferencestags %}

{% block title %}Inscription{% endblock %}

{% block content %}

<h2>Devenez membre des {% tp "site" "name_short" %}</h2>
<h3>Inscription</h3>

<form method="post" action=".">
	<p>Etre inscrit sur le site {% tp "site" "name2" %} vous permet de participer &agrave; la communaut&eacute;, d'&ecirc;tre mis au courant des derni&egrave;res sorties propos&eacute;es &#8230;</p>
	{{form.as_p}}
	<p><input class="awesome green" value="Valider" type="submit"></p>
</form>  
  
{% endblock %}

templates/accounts/validation.html
{% extends "base.html" %}

{% block title %}Validation de votre compte{% endblock %}

{% block content %}
<h1>Validation de votre compte</h1>

<p>Votre compte a bien &eacute;t&eacute; cr&eacute;&eacute; mais avant d'&ecirc;tre actif il doit &ecirc;tre valid&eacute; par les administrateurs du site.</p>
<p>Nous nous en occuperons aussi rapidement que possible.</p>
<p>Merci de votre patience.</p>
<p><a href="{% url root %}">Retour au site</a>.</p>

{% endblock %}