article/urls.py
from article.feeds import LatestArticlesFeed
from django.conf.urls.defaults import patterns, url

feeds = {
    'latest': LatestArticlesFeed,
}

urlpatterns = patterns('',
    url(r'^$', 'article.views.list_articles', name="articles"),
    url(r'^add/$', 'article.forms.create_new_article', name='addarticle'),
    url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}, name="feedarticles"),
    url(r'^(?P<slug>[\-\d\w]+)/$', 'article.views.view_article', name="viewarticle"),
    url(r'^(?P<slug>[\-\d\w]+)/edit/$', 'article.forms.edit_article', name='editarticle'),
    url(r'^(?P<slug>[\-\d\w]+)/delete/$', 'article.forms.delete_article', name='deletearticle'),
    url(r'^(?P<slug>[\-\d\w]+)/subscribe/$', 'article.forms.subscribe_article_slug', name='subscribearticle'),
    url(r'^(?P<slug>[\-\d\w]+)/unsubscribe/$', 'article.forms.unsubscribe_article_slug', name='unsubscribearticle'),
 )

urls.py
from django.conf.urls.defaults import patterns, url, include
from django.contrib import admin
from djblets.util.misc import generate_cache_serials
from django.conf import settings
import os
from admin.forms import GeneralSettingsForm

# Generate cache serials
generate_cache_serials()

if not admin.site._registry:
    admin.autodiscover()

cal_path = os.path.dirname(__file__)
urlpatterns = patterns('',
    (r'^robots\.txt$', 'django.views.static.serve', {'path':'robots.txt', 'document_root': cal_path, 'show_indexes': True}),
    (r'^bc38928ca88b5eaeb8eac84640c15074\.txt$', 'django.views.static.serve', {'path':'bc38928ca88b5eaeb8eac84640c15074.txt', 'document_root': cal_path, 'show_indexes': True}),
    url(r'^search/$', 'django.views.generic.simple.direct_to_template', {'template':'search.html', 'extra_context':{'full':True}}, name="search"),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^article/', include('article.urls')),
    (r'^lien/', include('article.lien_urls')),
    (r'^account/', include('account.urls')),
    (r'^forum/', include('forum.urls')),
    (r'^galerie/', include('galerie.urls')),
    (r'^photologue/', include('photologue.urls')),
    (r'^sortie/', include('sortie.urls')),
    (r'^comment/', include('comment.urls')),
    (r'^captcha/', include('captcha.urls')),
    (r'^core/', include('core.urls')),
    (r'^matos/', include('matos.urls')),
    (r'^meteo/', include('meteo.urls')),
#    (r'^browse/(.*)', login_required(databrowse.site.root)),
)

# And the rest ...
urlpatterns += patterns('',
    url(r'^$', 'article.views.accueil', name="root"),
    url(r'^about/$', 'article.views.about', name="aboutus"),
    url(r'^contactus/$', 'account.forms.contact_us', name="contactus"),
    (r'^secure/(?P<path>.*)$', 'core.views.serve', {
        'show_indexes': True,
        'document_root': settings.SECURE_ROOT,
        }),
)

# Adding the site settings page
urlpatterns += patterns('',
    url(r'admin/settings/general/$', 'djblets.siteconfig.views.site_settings',
     {'form_class': GeneralSettingsForm}, name="site_setup"))

# Add static media
import djblets
import django.contrib.admin
djblets_media_path = os.path.join(os.path.dirname(djblets.__file__), 'media')
admin_media_path = os.path.join(os.path.dirname(django.contrib.admin.__file__), 'media')
urlpatterns += patterns('django.views.static',
    (r'^media/admin/(?P<path>.*)$', 'serve', {
        'show_indexes': True,
        'document_root': admin_media_path,
        }),
    (r'^media/djblets/(?P<path>.*)$', 'serve', {
        'show_indexes': True,
        'document_root': djblets_media_path,
        }),
    (r'^media/(?P<path>.*)$', 'serve', {
        'show_indexes': True,
        'document_root': settings.MEDIA_ROOT,
        }),
)

article/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from tagging.fields import TagField
from comment.models import Comment
from django.core.urlresolvers import reverse
from tagging.utils import parse_tag_input
from django.template.defaultfilters import slugify

tagfield_help_text = 'Separate tags with spaces, put quotes around multiple-word tags.'

class Article(models.Model):
    auteur = models.ForeignKey(User, related_name='auteur_set')
    titre = models.TextField()
    titre_slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    contenu = models.TextField()
    tags = TagField(help_text=tagfield_help_text, verbose_name='tags')
    comments = models.ManyToManyField(Comment, 
                                         related_name='article_comments_set',
                                         null=True, blank=True)
    date_publication = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "%s (%s - %s)" % (self.titre, self.auteur.username, self.date_publication)
    
    def get_absolute_url(self):
        return reverse("viewarticle", kwargs={'slug':self.titre_slug})
    
    def generate_slug(self):
        slug = slugify(self.titre)
        oldslug = self.titre_slug
        if oldslug:
            try:
                ArticleOldSlugs.objects.get_or_create(article=self, titre_slug=oldslug)
            except:
                pass

        if Article.objects.exclude(pk=self.pk).filter(titre_slug=slug).count() + ArticleOldSlugs.objects.exclude(article=self).filter(titre_slug=slug).count() > 0:
            slug = "%s-%s" % (slug, self.pk)
        self.titre_slug = slug
        self.save()
        
    def get_tags(self):
        tags = parse_tag_input(self.tags)
        return tags        

class ArticleOldSlugs(models.Model):
    article = models.ForeignKey(Article, related_name='article_oldslugs_set')
    titre_slug = models.SlugField(max_length=255, unique=True)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "%s" % (self.titre_slug)

class Lien(models.Model):
    titre = models.CharField(max_length=255)
    label = models.CharField(max_length=255)
    lien = models.CharField(max_length=255)
    disabled = models.BooleanField(default=False)
    ordre = models.IntegerField(default=-1)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "%s" % (self.titre)

article/views.py
# -*- coding: utf-8 -*-
from article.models import Article, ArticleOldSlugs
from django.http import Http404
from django.template.context import RequestContext
from django.shortcuts import render_to_response
import datetime
from django.contrib.auth.models import User

def list_articles(request, type='article', template_name='article/article_list.html'):
    articles = Article.objects.all()
    if type == 'article':
        articles = articles.exclude(tags__icontains="accueil").exclude(tags__icontains="lien")
    if type == 'accueil':
        articles = articles.filter(tags__icontains="accueil")
    if type == 'lien':
        articles = articles.filter(tags__icontains="lien")
    articles = articles.order_by('-date_publication')
    years = []
    for a in articles:
        if not a.date_publication.year in years:
            years.append(a.date_publication.year)
    year = request.GET.get("year", None)

    tags = request.GET.getlist('tag')
    if tags:
        for t in tags:
            articles = articles.filter(tags__icontains=t)
            
    auteur = request.GET.get('auteur')
    if auteur:
        try:
            auteur = User.objects.get(pk=int(auteur))
            articles = articles.filter(auteur=auteur)
        except:
            pass

    if not tags and not auteur:
        if not year:
            year = datetime.date.today().year
        else:
            year = int(year)
        articles = articles.filter(date_publication__year=year)

    articlescount = 0
    try:
        articlescount = articles.count()
    except:
        pass
    return render_to_response(template_name,
                              RequestContext(request,
                                             {'articles': articles,
                                              'tags': tags,
                                              'years': years,
                                              'year': year,
                                              'auteur': auteur,
                                              'articlescount': articlescount,
                                              }))


def view_article(request, slug, template_name='article/article_view.html'):
    try:
        article = Article.objects.get(titre_slug=slug)
    except Article.DoesNotExist:
        try:
            article = Article.objects.get(pk=int(slug))
        except:
            try:
                old = ArticleOldSlugs.objects.get(titre_slug=slug)
                if old:
                    article = old.article
                else:
                    raise Http404("L'article n'existe pas")
            except ArticleOldSlugs.DoesNotExist:
                raise Http404("L'article n'existe pas")
    return internal_view_article(request, article, template_name)

def internal_view_article(request, article, template_name='article/article_view.html', urlretour=None):
    date_publication = article.date_publication if article.date_publication else datetime.datetime.now()
    canbeedited = not urlretour and (request.user == article.auteur or request.user.is_superuser)
    issubscribed = False
    if request.user.is_authenticated() and article.pk:
        issubscribed = request.user.get_profile() in article.articles_suivis_set.all()
    return render_to_response(template_name, RequestContext(request, 
                                                            {'article': article,
                                                             'date_publication': date_publication,
                                                             'urlretour': urlretour,
                                                             'canbeedited': canbeedited,
                                                             'issubscribed': issubscribed,
                                                             'full': True,
                                                             }))

def accueil(request, template_name='article/accueil.html'):
    allarticles = Article.objects.all()
    allarticles = allarticles.exclude(tags__icontains="accueil").exclude(tags__icontains="lien")
    allarticles = allarticles.order_by('-date_publication')
    years = []
    for a in allarticles:
        if not a.date_publication.year in years:
            years.append(a.date_publication.year)
    year = request.GET.get("year", None)
    if not year:
        year = datetime.date.today().year
    else:
        year = int(year)
    articles = allarticles.filter(date_publication__year=year)
    articlescount = articles.count()
    if allarticles.count() > 0:
        while articlescount == 0:
            year = year - 1
            articles = allarticles.filter(date_publication__year=year)
            articlescount = articles.count()

    return render_to_response(template_name,
                              RequestContext(request,
                                             {'articles': articles,
                                              'years': years,
                                              'year': year,
                                              'articlescount': articlescount,
                                              }))

def about(request, template_name='article/about.html'):
    article = Article.objects.filter(tags__icontains="accueil").order_by("pk")[0]
    return render_to_response(template_name, RequestContext(request, 
                                                            {'article': article,
                                                             'full': True,
                                                             }))

templates/article/about.html
{% extends "base.html" %}
{% block title %}Pr&eacute;sentation du Club{% endblock %}

{% block content %}
<div class="actualite">
	<h2 class="doc-title">{{ article.titre }}</h2>
	<div class="doc-content">
		<p>{{ article.contenu|safe }}</p>  
	</div> <!-- doc-content -->
</div>
{% endblock %}

templates/article/accueil.html
{% extends "base.html" %}
{% load coretags %}
{% load preferencestags %}

{% block title %}{% tp "site" "name" %}{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{MEDIA_URL}}js/article.js?{{MEDIA_SERIAL}}"></script>
{% endblock %}

{% block content %}
 {% for article in articles %}

	<div class="newsblock{% ifequal forloop.counter 1 %} first{% endifequal %}">
		<h2 class="title">
	        <a href="{{ article.get_absolute_url }}">{{ article.titre }}</a>
	    </h2>
	    
	    <div class="meta">
	    	<span class="metafirst">
	    	par 
	    	{{ article.auteur.username }} 
	    	le  {{ article.date_publication.date|date:"l d F Y" }} &agrave; {{ article.date_publication.time }}
	    	</span>
	    	<a class="hometip comc" href="{{ article.get_absolute_url }}#commentaires" title="{{article.comments.all.count}} commentaires">{{article.comments.all.count}} commentaires</a>
	    </div>
	    {{ article.auteur.get_profile.get_html_illustration|safe }}
	    <div class="texte">
	    <p>{{ article.contenu|resume|safe }}</p>
	    <a class="readnext" title="Lire la suite de {{ article.titre }}" href="{{ article.get_absolute_url }}">Lire la suite &raquo;</a>
	    </div>
	</div>

 {% endfor %}

<p class="pagination">
{% for y in years %}
	<a{% if year == y %} class="active"{% endif %} title="{{y}}" href="{% url root %}?year={{y}}">{{y}}</a>
{% endfor %}
</p>

{% endblock %}

templates/article/article_add.html
{% extends "base.html" %}
{% block title %}Ajout d'un article{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{MEDIA_URL}}js/comment_textarea.js?{{MEDIA_SERIAL}}"></script>
{% endblock %}

{% block content %}
<h2>Ajout d'un article</h2>

<p class="warn">
Commencez la r&eacute;daction de l'article avec un petit paragraphe (en passant &agrave; la ligne pour la suite de l'article) qui r&eacute;sume son contenu.<br>En effet ce premier paragraphe sera ensuite r&eacute;utilis&eacute; comme aper&ccedil;u du contenu de l'article.
</p>

<form id="addarticleform" method="POST" action="{% url addarticle %}">
    {{ form.as_p }}
	<input class="awesome green" type="submit" name="submit"  value="Ajouter" />
	<input class="awesome orange" type="submit" name="preview" id="previewbtn" value="Pr&eacute;visualiser" />
</form>

{% endblock %}

templates/article/article_edit.html
{% extends "base.html" %}
{% block title %}Edition de {{ article.titre }}{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{MEDIA_URL}}js/comment_textarea.js?{{MEDIA_SERIAL}}"></script>
{% endblock %}

{% block content %}
<h2>Modification de l'article "{{ article.titre }}"</h2>

<form id="editarticleform" method="POST" action="{% url editarticle article.titre_slug %}">
	{{ form.as_p }}
	<input class="awesome green" type="submit" name="submit"  value="Valider" />
	<input class="awesome orange" type="submit" name="preview" id="previewbtn" value="Pr&eacute;visualiser" />
</form>

{% endblock %}

templates/article/article_list.html
{% extends "base.html" %}
{% load coretags %}
{% load articletags %}

{% block title %}Articles{% endblock %}

{% block content %}
<h2>Liste des articles{% if tags %} {{tags|join:", "}}{% endif %}{% if auteur %} par {{auteur.username}}{% endif %}</h2>

{% if perms.article.add_article %}
<p class="suggest right"><a class="awesome blue" href="{% url addarticle %}">Ecrire un nouvel article</a></p>
{% endif %}

<p><a href="{% url feedarticles 'latest' %}"><img alt="" src="{{MEDIA_URL}}css/img/rss.gif"> S'abonner au flux RSS</a></p>
<p>{{articlescount}} articles en ligne{% if year %} pour l'ann&eacute;e {{year}}{% endif %}</p>

<ul class="newslist">
 {% for article in articles %}
	<li class="{% cycle 'even' 'odd' %}{% ifequal forloop.counter 1 %} first{% endifequal %}">
    {{ article.auteur.get_profile.get_html_illustration|safe }}
	<span class="titre"><a title="{{ article.titre }}" href="{{ article.get_absolute_url }}">{{ article.titre }}</a></span>
	<span class="meta">
		Le {{ article.date_publication.date|date:"l d F Y" }} &agrave; {{ article.date_publication.time }} par {{ article.auteur.username }}, <a href="{{ article.get_absolute_url }}#commentaires">{{article.comments.all.count}} commentaires</a>
   		{% article_tags_entry article %}
	</span>
	</li>
 {% endfor %}
</ul>

<p class="pagination">
{% for y in years %}
	<a{% if year == y %} class="active"{% endif %} title="{{y}}" href="{% url articles %}?year={{y}}">{{y}}</a>
{% endfor %}
</p>

{% endblock %}

templates/article/article_tags_entry.html
{% if qspertag %}<br>Tags :
{% for t in qspertag %}{% ifnotequal forloop.counter 1 %}, {% endifnotequal %}{{t|safe}}{% endfor %}
{% endif %}

templates/article/article_view.html
{% extends "base.html" %}
{% load commenttags %}
{% load articletags %}
{% block title %}{{ article.titre }}{% endblock %}

{% block content %}
<div class="actualite">
	<h2 class="doc-title">{{ article.titre }} {% if user == article.auteur or user.is_superuser %}<a title="Supprimer {{article.titre}}" href="{% url deletearticle article.titre_slug %}"><img alt="" src="{{MEDIA_URL}}images/icon_deletelink.gif?{{MEDIA_SERIAL}}"></a>{% endif %}</h2>

{% if user.is_authenticated and not urlretour %}
 <p>
 {% if issubscribed %}
  Si vous voulez <a href="{% url unsubscribearticle article.titre_slug %}">ne plus suivre cet article</a>.
 {% else %}
  Si vous voulez <a href="{% url subscribearticle article.titre_slug %}">suivre cet article</a>.
 {% endif %}
 </p>
{% endif %}

    <div class="auteur ">
    	{{ article.auteur.get_profile.get_html_avatar|safe }}
		<p>Article par <a title="{{article.auteur.username}}" href="{% url viewprofil user_pk=article.auteur.pk %}">{{ article.auteur.username }}</a>
		<span class="edit">{% if canbeedited %}<a title="Editer l'article" href="{% url editarticle article.titre_slug %}">{% endif %}<img alt="Editer l'article" src="{{MEDIA_URL}}css/img/picto-edit.png" />{% if canbeedited %}</a>{% endif %}</span>
		<br>
      	<span class="meta">
      		Mis &agrave; jour le {{ date_publication.date|date:"l d F Y" }} &agrave; {{ date_publication.time }}
      		{% article_tags_entry article %}
      	</span>
      	</p>
    </div>
    <div class="auteur-end"></div>
    {% if canbeedited %}
	<p class="suggestbottom right">
		<a title="Editer l'article" class="awesome yellow" href="{% url editarticle article.titre_slug %}">Editer l'article</a>
	</p>
	{% endif %}
 
	<div class="doc-content">
		<p>{{ article.contenu|safe }}</p>  
	</div> <!-- doc-content -->


</div>

{% if urlretour %}
<form method="POST" action="{{urlretour}}" >
	<input type="hidden" name="editpreview" value="True" />
	<input type="hidden" name="auteur" value="{{article.auteur.pk}}" />
	<input type="hidden" name="titre" value="{{article.titre}}" />
	<input type="hidden" name="contenu" value="{{article.contenu}}" />
	<input type="hidden" name="tags" value="{{article.tags}}" />
 	<input class="awesome orange" type="submit" value="Retour &agrave; l'&eacute;dition" />
</form>
{% else %}
{% comments_entry 'article' article.pk article.comments.all %}
{% endif %}

{% endblock %}

templates/article/lien_add.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load djblets_utils %}
{% load articletags %}
{% block title %}Ajout de lien{% endblock %}

{% block content %}
<div class="boxmargin">
{% box "loginform" %}
<form id="addlienform" method="POST" action="{% url addlien %}">
 <h1 class="title">Ajout de lien</h1>
 <div class="main">
 {% if error %}
 {%  errorbox %}
    {{ error }}
 {%  enderrorbox %}
 {% endif %}
<table>
    <tbody>
    {{ form }}
    </tbody>
</table>
 </div>
 <input type="submit" value="Ajouter" />
</form>
</div>
{% endbox %}
{% endblock %}

templates/article/lien_nav.html
{% load articletags %}
{% if allliens %}
    <tr>
     <td colspan="2" class="nav_header">Liens{% if perms.article.add_lien %}<span style="float: right; font-size: 10px"><a href="{% url addlien %}">(+)</a></span>{% endif %}</td>
    </tr>
{% for l in allliens %}
    <tr onclick="javascript:window.location=&quot;{{ l.url }}&quot;; return false;" class="unselected">
     <td colspan="2" class="summary sub-item"><a href="{{ a.url }}" title="{{ l.description }}">{{ l.titre }}</a></td>
    </tr>
{% endfor %}
    <tr><td colspan="2" class="nav_separator"></td></tr>
{% endif %}

templates/article/mail_new_article.html
{% load coretags %}
{% load preferencestags %}
<p>Bonjour {{ profil.username }},</p>
<p>Vous recevez ce mail car vous avez demand&eacute; &agrave; &ecirc;tre notifi&eacute; lorsqu'un nouvel article est publi&eacute; sur le site {% tp "site" "name2" %}</p>
<p><strong>{{ article.auteur.username }}</strong> a publi&eacute; l'article <a href="http://{{ domain }}{{ article.get_absolute_url }}">{{ article.titre }}</a></p>
<p>R&eacute;sum&eacute; : {{ article.contenu|resume|safe }}</p>
<a class="readnext" title="Lire la suite de {{ article.titre }}" href="http://{{ domain }}{{ article.get_absolute_url }}">Lire la suite &raquo;</a>
<p>Vous pouvez demander &agrave; ne plus &ecirc;tre notifi&eacute; <a href="http://{{ domain }}{% url editprofil %}">ici</a>.</p>
<p>Merci d'utiliser notre site.<br> - {% tp "site" "sign" %} -</p>

templates/article/pagination_entry.html

<p class="pagination">
	<span>
	    <a href="?page=1" title="Premi&egrave;re page">D&eacute;but</a>
	</span>

	{% if objects_pagination.has_previous %}
	    <a href="?page={{ objects_pagination.previous_page_number }}" title="Page pr&eacute;c&eacute;dente"><</a>
	{% endif %}
	
	{% for i in paginator.page_range %}
		{% ifequal i objects_pagination.number %}
		<b>{{i}}</b>
		{% else %}
		<a href="?page={{i}}" title="Page {{i}}">{{i}}</a>
		{% endifequal %}
	{% endfor %}
	
	{% if objects_pagination.has_next %}
	    <a href="?page={{ objects_pagination.next_page_number }}" title="Page suivante">></a>
	{% endif %}
	
	<span>
	    <a href="?page={{ objects_pagination.paginator.num_pages }}" title="Derni&egrave;re page">Fin</a>
	</span>
</p>

templates/article/tag_nav.html
{% load articletags %}
{% if alltags %}
    <tr>
     <td colspan="2" class="nav_header"><a href="{% url articles %}">Articles par tag</a></td>
    </tr>
{% for t in alltags %}
{%  tags_entry "sub-item" t.name "bytags" t %}
{% endfor %}
    <tr><td colspan="2" class="nav_separator"></td></tr>
{% endif %}

templates/article/tags_entry.html
    <tr onclick="javascript:window.location=&quot;{% url articles %}?view={{view}}{% if tag %}&amp;tag={{tag}}{% endif %}&quot;; return false;"{% if selected %} class="selected"{% else %} class="unselected"{% endif %}>
     <td class="summary {{level}}"><a href="{% url articles %}?view={{view}}{% if tag %}&amp;tag={{tag}}{% endif %}">{{text}}</a></td>
     <td>{% if show_count %}{{count}}{% endif %}</td>
    </tr>